---
- name: Restart Mariadb
  throttle: 1
  block:
    - name: Restart MariaDB
      service:
        name: mariadb
        state: restarted
    - name: Wait until MariaDB has joined the cluster
      shell: "/usr/local/bin/clustercheck"
      register: node_status
      until: node_status.rc == 0
      retries: 90
      delay: 10
      when: mariadb_cluster|default(false)
